let siteConfigPromise;
let activeCampPricing={1:{1:185,2:333,3:471,4:592},2:{1:333,2:599,3:849,4:1065},3:{1:471,2:849,3:1202,4:1509}};
const socialLinks={whatsapp:'https://wa.me/96597913191',instagram:'https://www.instagram.com/apexcamp.co/',tiktok:'https://www.tiktok.com/@apexcamp'};
const campMedia={activityImage:'https://raw.githubusercontent.com/Medyconz/ApexCamp/55c3735099d518a629ecef23a41eab51acfcb80a/assets/WhatsApp%20Image%202026-05-15%20at%2013.18.56.jpeg',highlightVideo:'assets/apex-camp-home.mp4'};
const socialIcons={whatsapp:'<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12.04 2a9.9 9.9 0 0 0-8.5 14.99L2.25 22l5.14-1.22A9.96 9.96 0 1 0 12.04 2Zm0 1.88a8.08 8.08 0 0 1 6.93 12.22 8.05 8.05 0 0 1-9.8 3.19l-.35-.16-3.03.72.76-2.95-.19-.37A8.08 8.08 0 0 1 12.04 3.88Zm-3.4 3.77c-.19 0-.5.07-.76.35-.26.28-1 1-1 2.43s1.03 2.81 1.18 3c.14.19 2.03 3.22 5 4.39 2.47.97 2.97.78 3.51.73.54-.05 1.74-.71 1.98-1.4.25-.68.25-1.27.18-1.4-.07-.12-.27-.2-.56-.35-.29-.14-1.73-.85-1.99-.95-.27-.1-.46-.14-.66.15-.19.29-.75.95-.92 1.14-.17.2-.34.22-.63.08-.29-.15-1.22-.45-2.33-1.44-.86-.77-1.44-1.72-1.61-2-.17-.29-.02-.44.13-.58.13-.13.29-.34.43-.51.15-.17.2-.29.29-.48.1-.19.05-.36-.02-.51-.07-.15-.65-1.57-.9-2.15-.23-.56-.47-.48-.65-.49h-.67Z"/></svg>',instagram:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.2" y="3.2" width="17.6" height="17.6" rx="5.2" ry="5.2" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="4.1" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="17.25" cy="6.75" r="1.25" fill="currentColor"/></svg>',tiktok:'<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M16.5 3c.28 2.05 1.43 3.42 3.5 3.7v3.15a7.2 7.2 0 0 1-3.55-1.04v5.83c0 3.11-2.05 5.36-5.2 5.36-2.78 0-5.25-1.82-5.25-4.82 0-3.3 2.8-5.08 5.72-4.54v3.2c-1.33-.42-2.65.22-2.65 1.34 0 1.02.9 1.63 1.88 1.63 1.28 0 2.14-.72 2.14-2.35V3h3.41Z"/></svg>'};

function ensureEnhancementStyles(){if(document.querySelector('link[href="enhancements.css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='enhancements.css';document.head.appendChild(link)}
function getSiteConfig(){if(!siteConfigPromise){siteConfigPromise=fetch('/api/site-config').then((response)=>response.ok?response.json():Promise.reject(new Error('Site settings are not available.')))}return siteConfigPromise}
function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function escapeAttr(value){return escapeHtml(value).replaceAll('`','&#096;')}

function initMobileNav(){document.querySelectorAll('.site-header').forEach((header)=>{const nav=header.querySelector('.site-nav');if(!nav||header.querySelector('.menu-toggle'))return;const button=document.createElement('button');button.className='menu-toggle';button.type='button';button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Open menu');button.innerHTML='<span></span><span></span><span></span>';header.insertBefore(button,nav);button.addEventListener('click',()=>{const open=header.classList.toggle('nav-open');button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Close menu':'Open menu')});nav.querySelectorAll('a').forEach((link)=>link.addEventListener('click',()=>{header.classList.remove('nav-open');button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Open menu')}))})}

function initSocialFloaters(){if(document.body.classList.contains('admin-page')||document.querySelector('.social-floaters'))return;const nav=document.createElement('nav');nav.className='social-floaters';nav.setAttribute('aria-label','Apex Camp social links');nav.innerHTML=`<a class="social-floater whatsapp" href="${socialLinks.whatsapp}" target="_blank" rel="noopener" aria-label="Message Apex Camp on WhatsApp"><span aria-hidden="true">${socialIcons.whatsapp}</span><b>WhatsApp</b></a><a class="social-floater instagram" href="${socialLinks.instagram}" target="_blank" rel="noopener" aria-label="Open Apex Camp Instagram"><span aria-hidden="true">${socialIcons.instagram}</span><b>Instagram</b></a><a class="social-floater tiktok" href="${socialLinks.tiktok}" target="_blank" rel="noopener" aria-label="Open Apex Camp TikTok"><span aria-hidden="true">${socialIcons.tiktok}</span><b>TikTok</b></a>`;document.body.appendChild(nav)}

function renderSocialHighlights(){if(document.body.classList.contains('admin-page')||document.querySelector('.social-highlight'))return;const main=document.querySelector('main');if(!main)return;const footer=document.querySelector('footer');const section=document.createElement('section');section.className='section social-highlight';section.setAttribute('aria-labelledby','social-highlight-title');section.innerHTML=`<div class="social-highlight-heading"><div><p class="eyebrow">Apex Camp on social</p><h2 id="social-highlight-title">See the camp moments parents talk about.</h2><p>Follow Apex Camp Kuwait for activity photos, short videos, announcements, and day-by-day camp energy.</p></div><a class="button secondary" href="${socialLinks.whatsapp}" target="_blank" rel="noopener">Ask on WhatsApp</a></div><div class="social-grid"><a class="social-card social-card-video" href="${socialLinks.tiktok}" target="_blank" rel="noopener"><video muted loop playsinline preload="metadata" poster="Profile%20Picture%201.jpg.jpeg" aria-label="Apex Camp video preview"><source src="${campMedia.highlightVideo}" type="video/mp4"><source src="assets/WhatsApp%20Video%202026-05-15%20at%2013.15.58.mp4" type="video/mp4"></video><span>TikTok @apexcamp</span><strong>Videos from camp days</strong><small>Open TikTok for quick clips and activity highlights.</small></a><a class="social-card" href="${socialLinks.instagram}" target="_blank" rel="noopener"><img src="${campMedia.activityImage}" alt="Apex Camp activity photo preview"><span>Instagram @apexcamp.co</span><strong>Photos and reels</strong><small>Follow the Instagram page for images, reels, and updates.</small></a><a class="social-card social-card-contact" href="${socialLinks.whatsapp}" target="_blank" rel="noopener"><span>WhatsApp 97913191</span><strong>Questions before registering?</strong><small>Message the team directly from your phone or browser.</small></a></div>`;if(footer?.parentNode)footer.parentNode.insertBefore(section,footer);else main.appendChild(section);section.querySelectorAll('video').forEach((video)=>{video.addEventListener('pointerenter',()=>video.play().catch(()=>{}));video.addEventListener('focus',()=>video.play().catch(()=>{}))})}

function normalizePricing(pricing){if(!pricing)return activeCampPricing;if(Array.isArray(pricing)){return pricing.reduce((matrix,row)=>{const children=Number(row.children);if(!children)return matrix;matrix[children]={1:Number(row.week_1)||0,2:Number(row.week_2)||0,3:Number(row.week_3)||0,4:Number(row.week_4)||0};return matrix},{})}return pricing}
async function renderCampWeeks(config){const target=document.querySelector('[data-required-group="camp_weeks"] .choice-list');if(!target)return;try{config=config||await getSiteConfig();const weeks=(config.camp_weeks||[]).filter((week)=>week.active!==false);if(!weeks.length)return;target.innerHTML=weeks.map((week)=>`<label class="choice"><input type="checkbox" name="camp_weeks" value="${escapeAttr(week.label)}"> ${escapeHtml(week.label)}</label>`).join('')}catch(error){console.warn(error)}}
function renderPricingTable(config){if(config?.camp_pricing)activeCampPricing=normalizePricing(config.camp_pricing);const body=document.querySelector('.pricing-table tbody');if(!body)return;body.innerHTML=[1,2,3].map((children)=>{const row=activeCampPricing[children]||{};return `<tr><th>${children} ${children===1?'Child':'Children'}</th><td>${formatPrice(row[1])}</td><td>${formatPrice(row[2])}</td><td>${formatPrice(row[3])}</td><td>${formatPrice(row[4])}</td></tr>`}).join('')}
function renderPaymentInfo(config){const panel=document.querySelector('#payment-info');if(!panel)return;const settings=config?.payment_settings||{};const instructions=settings.instructions||'Your registration will be saved first. The Apex Camp team will contact you to confirm availability and payment details.';const link=settings.payment_link||'';panel.querySelector('[data-payment-instructions]').textContent=instructions;const linkTarget=panel.querySelector('[data-payment-link]');if(link){linkTarget.href=link;linkTarget.hidden=false}else{linkTarget.hidden=true}}
async function renderMerch(config){const target=document.querySelector('#merch-products');if(!target)return;try{config=config||await getSiteConfig();const products=(config.merch_products||[]).filter((product)=>product.active!==false);if(!products.length){target.innerHTML='<article><h2>Merch coming soon</h2><p>Apex Camp products will appear here once they are added in the admin dashboard.</p></article>';return}target.innerHTML=products.map((product)=>`<article class="merch-card">${product.image_url?`<img src="${escapeAttr(product.image_url)}" alt="${escapeAttr(product.name)}">`:''}<div><h2>${escapeHtml(product.name)}</h2>${product.price?`<strong>${escapeHtml(product.price)}</strong>`:''}${product.description?`<p>${escapeHtml(product.description)}</p>`:''}${product.buy_url?`<a class="button" href="${escapeAttr(product.buy_url)}">Buy Now</a>`:''}</div></article>`).join('')}catch(error){target.innerHTML='<article><h2>Merch loading soon</h2><p>Please refresh in a moment.</p></article>'}}

function initRegistrationTools(){const form=document.querySelector('.camp-form[data-endpoint="/api/register"]');if(!form)return;const childSelect=form.querySelector('#child-count');form.querySelector('[data-required-group="camp_weeks"]')?.addEventListener('change',()=>updateRegistrationPrice(form));childSelect?.addEventListener('change',()=>{updateStudentSections(form);updateRegistrationPrice(form)});updateStudentSections(form);updateRegistrationPrice(form)}
function updateStudentSections(form){const count=Number(form.querySelector('#child-count')?.value||1);form.querySelectorAll('.student-section').forEach((section)=>{const studentNumber=Number(section.dataset.student||1);const active=studentNumber<=count;section.hidden=!active;section.querySelectorAll('[data-required-when-active]').forEach((field)=>{field.required=active})})}
function updateRegistrationPrice(form){const weekCount=form.querySelectorAll('input[name="camp_weeks"]:checked').length;const childCount=Number(form.querySelector('#child-count')?.value||1);const estimate=form.querySelector('#price-estimate');const totalWeeks=form.querySelector('#total-weeks');const estimatedTotal=form.querySelector('#estimated-total-kd');if(totalWeeks)totalWeeks.value=String(weekCount);if(estimatedTotal)estimatedTotal.value='';if(!estimate)return;if(!weekCount){estimate.textContent='Choose camp dates to see the estimated total.';return}if(weekCount>4){estimate.textContent=`${weekCount} weeks selected for ${childCount} ${childCount===1?'child':'children'}. The Apex Camp team will confirm pricing for 5 or more weeks.`;return}const price=activeCampPricing[childCount]?.[weekCount];if(estimatedTotal&&price)estimatedTotal.value=String(price);estimate.textContent=price?`Estimated total: ${price} KD for ${childCount} ${childCount===1?'child':'children'} and ${weekCount} ${weekCount===1?'week':'weeks'}.`:'The Apex Camp team will confirm pricing for this selection.'}
function formatPrice(value){const number=Number(value);return number?`${number} KD`:'Confirm'}
function showRegistrationSummary(form,data,result){const target=document.querySelector('#registration-summary');if(!target)return;const weeks=Array.isArray(data.camp_weeks)?data.camp_weeks:[data.camp_weeks].filter(Boolean);const childCount=Number(data.child_count||1);const total=data.estimated_total_kd?`${data.estimated_total_kd} KD`:'To be confirmed';target.hidden=false;target.innerHTML=`<h2>Registration saved</h2><p>${escapeHtml(result.message||'Thank you. Your form was saved for the Apex Camp team.')}</p><dl><div><dt>Children</dt><dd>${childCount}</dd></div><div><dt>Weeks</dt><dd>${weeks.length}</dd></div><div><dt>Estimated total</dt><dd>${escapeHtml(total)}</dd></div><div><dt>Selected dates</dt><dd>${escapeHtml(weeks.join(', '))}</dd></div></dl><p class="form-hint">Apex Camp will contact you using the parent/guardian details to confirm availability and payment.</p>`;target.scrollIntoView({behavior:'smooth',block:'nearest'})}
function fileToUpload(file){return new Promise((resolve,reject)=>{if(!file||!file.name||!file.size){resolve('');return}if(file.size>4*1024*1024){reject(new Error(`${file.name} must be smaller than 4 MB.`));return}const reader=new FileReader();reader.onload=()=>resolve({name:file.name,type:file.type||'application/octet-stream',size:file.size,data_url:reader.result});reader.onerror=()=>reject(new Error(`Could not read ${file.name}.`));reader.readAsDataURL(file)})}
async function formDataToJson(form){const data={};for(const [key,value] of new FormData(form).entries()){const prepared=value instanceof File?await fileToUpload(value):value;if(prepared==='')continue;if(data[key]){data[key]=Array.isArray(data[key])?data[key]:[data[key]];data[key].push(prepared)}else data[key]=prepared}return data}
async function initDynamicSite(){ensureEnhancementStyles();initMobileNav();initSocialFloaters();renderSocialHighlights();try{const config=await getSiteConfig();await renderCampWeeks(config);renderPricingTable(config);renderPaymentInfo(config);await renderMerch(config)}catch(error){renderPricingTable();renderPaymentInfo();await renderMerch()}initRegistrationTools()}
initDynamicSite();

document.querySelectorAll('.camp-form').forEach((form)=>{const message=form.querySelector('.form-message');form.addEventListener('submit',async(event)=>{if(!form.dataset.endpoint)return;event.preventDefault();if(form.dataset.endpoint==='/api/register')updateRegistrationPrice(form);const missingGroup=[...form.querySelectorAll('[data-required-group]')].find((group)=>!group.querySelector('input[type="checkbox"]:checked'));if(missingGroup){const legend=missingGroup.querySelector('legend')?.textContent||'This section';if(message)message.textContent=`Please choose at least one option for ${legend}.`;missingGroup.querySelector('input[type="checkbox"]')?.focus();return}if(!form.checkValidity()){form.reportValidity();if(message)message.textContent='Please complete the required fields.';return}const button=form.querySelector('button[type="submit"]');const oldLabel=button?button.textContent:'';if(button){button.disabled=true;button.textContent='Submitting...'}if(message)message.textContent='Sending your form...';try{const data=await formDataToJson(form);const response=await fetch(form.dataset.endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(data)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'The form could not be submitted.');if(form.dataset.endpoint==='/api/register')showRegistrationSummary(form,data,result);form.reset();if(form.dataset.endpoint==='/api/register'){updateStudentSections(form);updateRegistrationPrice(form)}if(message)message.textContent=result.message||'Thank you. Your form was saved for the Apex Camp team.'}catch(error){if(message)message.textContent=error.message||'The backend is not reachable yet.'}finally{if(button){button.disabled=false;button.textContent=oldLabel}}})});
